<?php

namespace App\Filament\Resources;

use App\Filament\Resources\CasinoGamesSalsaResource\Pages;
use App\Filament\Resources\CasinoGamesSalsaResource\RelationManagers;
use App\Models\CasinoCategory;
use App\Models\CasinoGamesSalsa;
use App\Models\CasinoGamesSlotgrator;
use Carbon\Carbon;
use Filament\Forms;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class CasinoGamesSalsaResource extends Resource
{
    protected static ?string $model = CasinoGamesSalsa::class;

    protected static ?string $navigationIcon = 'heroicon-o-puzzle-piece';

    protected static ?string $navigationLabel = 'Jogos Salsa';

    protected static ?string $modelLabel = 'Jogos Salsa';

    /**
     * @return string|null
     */
    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::where('active', 1)->count(); // TODO: Change the autogenerated stub
    }


    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Jogos Salsa')
                    ->description('Formulário do jogo salsa')
                    ->schema([
                        Forms\Components\Select::make('casino_category_id')
                            ->label('Categoria')
                            ->placeholder('Selecione uma categoria')
                            ->relationship(name: 'category', titleAttribute: 'name')
                            ->options(
                                fn($get) => CasinoCategory::query()
                                    ->pluck('name', 'id')
                            )
                            ->searchable()
                            ->preload()
                            ->live()
                            ->columnSpanFull(),
                        Forms\Components\TextInput::make('name')
                            ->label('Nome')
                            ->placeholder('Digite o nome do jogo')
                            ->required()
                            ->maxLength(191),
                        Forms\Components\Group::make()
                            ->schema([
                                Forms\Components\Select::make('game_type')
                                    ->label('Selecione o Tipode Jogo')
                                    ->options([
                                        'FREE' => 'FREE',
                                        'CHARGED' => 'CHARGED',
                                    ]),
                                Forms\Components\TextInput::make('game_label')
                                    ->label('Game Label')
                                    ->placeholder('Digite a label do jogo')
                                    ->required()
                                    ->maxLength(191),
                                Forms\Components\TextInput::make('game_code')
                                    ->label('Game Code')
                                    ->placeholder('Digite a código do jogo')
                                    ->required()
                                    ->maxLength(191),
                            ])->columns(3),
                        Forms\Components\TextInput::make('type')
                            ->label('Tipo')
                            ->placeholder('Digite o tipo do jogo')
                            ->required()
                            ->maxLength(50),
                        Forms\Components\Group::make()
                            ->schema([
                                Forms\Components\TextInput::make('provider')
                                    ->label('Provedor')
                                    ->placeholder('Digite o provedor do jogo')
                                    ->required()
                                    ->maxLength(50),
                                Forms\Components\Select::make('provider_service')
                                    ->label('Serviço Provedor')
                                    ->options([
                                        'salsa' => 'Salsa'
                                    ])
                            ])->columns(2),

                        Forms\Components\FileUpload::make('image')
                            ->label('Imagem')
                            ->placeholder('Carregue a imagem do jogo')
                            ->image()
                            ->columnSpanFull()
                            ->required(),
                        Forms\Components\Toggle::make('active')
                            ->default(true)
                            ->required(),
                    ])->columns(2)
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\ImageColumn::make('image'),
                Tables\Columns\TextColumn::make('name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('game_label')
                    ->searchable(),
                Tables\Columns\TextColumn::make('game_code')
                    ->searchable(),
                Tables\Columns\TextColumn::make('type')
                    ->searchable(),
                Tables\Columns\TextColumn::make('provider')
                    ->searchable(),
                Tables\Columns\IconColumn::make('active')
                    ->boolean(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('Category')
                    ->relationship('category', 'name')
                    ->label('Selecione uma categoria')
                    ->indicator('Categoria'),
                Filter::make('created_at')
                    ->form([
                        DatePicker::make('created_from')->label('Data Inicial'),
                        DatePicker::make('created_until')->label('Data Final'),
                    ])
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['created_from'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '>=', $date),
                            )
                            ->when(
                                $data['created_until'],
                                fn (Builder $query, $date): Builder => $query->whereDate('created_at', '<=', $date),
                            );
                    })
                    ->indicateUsing(function (array $data): array {
                        $indicators = [];

                        if ($data['created_from'] ?? null) {
                            $indicators['created_from'] = 'Criação Inicial ' . Carbon::parse($data['created_from'])->toFormattedDateString();
                        }

                        if ($data['created_until'] ?? null) {
                            $indicators['created_until'] = 'Criação Final ' . Carbon::parse($data['created_until'])->toFormattedDateString();
                        }

                        return $indicators;
                    }),
                Tables\Filters\SelectFilter::make('provider')
                    ->label('Provedor')
                    ->options([
                        'Evoplay' => 'Evoplay',
                        'PGSoft' => 'PGSoft',
                    ])
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkAction::make('Ativar')
                    ->icon('heroicon-m-check')
                    ->requiresConfirmation()
                    ->action(function($records) {
                        return $records->each->update(['active' => 1]);
                    }),
                Tables\Actions\BulkAction::make('Desativar')
                    ->icon('heroicon-m-x-circle')
                    ->requiresConfirmation()
                    ->action(function($records) {
                        return $records->each(function($record) {
                            $id = $record->id;
                            CasinoGamesSlotgrator::where('id', $id)->update(['active' => 0]);
                        });
                    }),
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ])
            ->emptyStateActions([
                Tables\Actions\CreateAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListCasinoGamesSalsas::route('/'),
            'create' => Pages\CreateCasinoGamesSalsa::route('/create'),
            'edit' => Pages\EditCasinoGamesSalsa::route('/{record}/edit'),
        ];
    }
}
